fix: enhance Docker image existence check using Docker Hub API

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -38,21 +38,26 @@ jobs:
         run: |
           VERSION=$(grep -oP '(?<=<Version>)(.*)(?=</Version>)' **/*.csproj)
           echo "VERSION=$VERSION" >> $GITHUB_ENV
-          
+      
       # Docker Authentication
       - name: Log in to Docker Hub
         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
-        
-        # Check if the Docker image with the version already exists on Docker Hub
+      
+      # Check if Docker Image Exists on Docker Hub
       - name: Check if Docker Image Exists on Docker Hub
         id: check_image_exists
         run: |
           IMAGE_TAG="${{ secrets.DOCKER_USERNAME }}/blazor-frontend:${{ env.VERSION }}"
-          if docker pull $IMAGE_TAG; then
-            echo "Image $IMAGE_TAG already exists. Rejecting build.";
-            exit 1;  # Fail the pipeline if the image already exists
+          API_URL="https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_USERNAME }}/blazor-frontend/tags/${{ env.VERSION }}"
+          
+          # Check if image tag exists by calling Docker Hub API
+          response=$(curl -s -o /dev/null -w "%{http_code}" $API_URL)
+          
+          if [ "$response" -eq 200 ]; then
+          echo "Image $IMAGE_TAG already exists. Rejecting build.";
+          exit 1;  # Fail the pipeline if the image already exists
           else
-            echo "Image $IMAGE_TAG does not exist. Proceeding with build.";
+          echo "Image $IMAGE_TAG does not exist. Proceeding with build.";
           fi
       
       # Build and Tag Frontend Image
