fix: update GitHub Actions workflow to support release branch and improve Docker image checks

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -4,9 +4,11 @@ on:
   push:
     branches:
       - main
+      - release
   pull_request:
     branches:
       - main
+      - release
 
 jobs:
   build:
@@ -40,37 +42,36 @@ jobs:
           VERSION=$(grep -oP '(?<=<Version>)(.*)(?=</Version>)' **/*.csproj)
           echo "VERSION=$VERSION" >> $GITHUB_ENV
 
-      # Check if the Docker image with the version already exists on Docker Hub
+  push_image:
+    needs: build
+    if: github.ref == 'refs/heads/release'  # Run only for the release branch
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v4
+
+      - name: Log in to Docker Hub
+        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
+      
+      # Check if the Docker image with the version already exists
       - name: Check if Docker Image Exists on Docker Hub
         id: check_image_exists
         run: |
           IMAGE_TAG="${{ secrets.DOCKER_USERNAME }}/blazor-frontend:${{ env.VERSION }}"
-          if docker pull $IMAGE_TAG; then
-            echo "Image $IMAGE_TAG already exists. Rejecting build."
-            exit 1  # Fail the pipeline if the image already exists
+          if docker manifest inspect $IMAGE_TAG > /dev/null 2>&1; then
+            echo "Image $IMAGE_TAG already exists. Skipping push."
+            exit 1  # Fails the job if the image already exists
           else
             echo "Image $IMAGE_TAG does not exist. Proceeding with build."
           fi
-
-      # Docker Authentication
-      - name: Log in to Docker Hub
-        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
 
       - name: Build and Push Docker frontend Image
         uses: mr-smithers-excellent/docker-build-push@v6
         with:
           image: guillenmartins/blazor-frontend
           dockerfile: 'BlazorCrud/Dockerfile'
-          tags: ${{env.VERSION}},latest
-          registry: docker.io
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
-          
-      - name: Build and Push Docker backend Image
-        uses: mr-smithers-excellent/docker-build-push@v6
-        with:
-          image: guillenmartins/blazor-backend
-          tags: ${{env.VERSION}},latest
+          tags: ${{ env.VERSION }},latest
           registry: docker.io
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
