refactor: streamline Docker image build and push process in GitHub Actions

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -11,6 +11,7 @@ on:
 jobs:
   build:
     runs-on: ubuntu-latest
+
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4
@@ -45,27 +46,20 @@ jobs:
         run: |
           IMAGE_TAG="${{ secrets.DOCKER_USERNAME }}/blazor-frontend:${{ env.VERSION }}"
           if docker pull $IMAGE_TAG; then
-            echo "Image $IMAGE_TAG already exists. Rejecting build.";
-            exit 1;  # Fail the pipeline if the image already exists
+            echo "Image $IMAGE_TAG already exists. Rejecting build."
+            exit 1  # Fail the pipeline if the image already exists
           else
-            echo "Image $IMAGE_TAG does not exist. Proceeding with build.";
+            echo "Image $IMAGE_TAG does not exist. Proceeding with build."
           fi
 
       # Docker Authentication
       - name: Log in to Docker Hub
         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
 
-      # Build and Tag Frontend Image
-      - name: Build Frontend Image
-        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/blazor-frontend:${{ env.VERSION }} .
-
-      # Build and Tag Backend (Database) Image
-      - name: Build Backend Image
-        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/blazor-backend:${{ env.VERSION }} .
-
-      # Push Images to Docker Hub
-      - name: Push Frontend Image
-        run: docker push ${{ secrets.DOCKER_USERNAME }}/blazor-frontend:${{ env.VERSION }}
- 
-      - name: Push Backend Image
-        run: docker push ${{ secrets.DOCKER_USERNAME }}/blazor-backend:${{ env.VERSION }}
+      - name: Build and Push Docker Image
+        uses: mr-smithers-excellent/docker-build-push@v6
+        with:
+          image: guillenmartins/blazor-frontend:${{ env.VERSION }}
+          registry: docker.io
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
